name: Update set implementation lists
on:
  # push:
  #  branches: [master]
  workflow_dispatch:
concurrency:
  group: set-impl
  cancel-in-progress: true
jobs:
  update-set-impl-issues:
    runs-on: ubuntu-latest
    steps:
      #- uses: github/checkout@v3
      - name: Get issues
        uses: actions-cool/issues-helper@v3.4.0
        id: setimplissues
        with:
          actions: 'find-issues'
          labels: 'tracking set'
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install mustache
        shell: bash
        
      - uses: actions/github-script@v6.4.1
        id: updateissues
        with:
          script: |
            const mustache = require('mustache')
            const fs = require('fs')
            
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'tracking set'
            });
            console.log("Found list of existing issues:", issues)
            
            issues.forEach(issue => {
              console.log(issue.title);
            })
